import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  username: text('username').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});

export const repos = sqliteTable('repos', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull().references(() => users.id),
  name: text('name').notNull(),
  backendType: text('backend_type').notNull(),
  repoUrl: text('repo_url').notNull(),
  credentialsEncrypted: text('credentials_encrypted').notNull(),
  credentialsIv: text('credentials_iv').notNull(),
  credentialsTag: text('credentials_tag').notNull(),
  status: text('status').notNull().default('unknown'),
  lastCheckedAt: integer('last_checked_at', { mode: 'timestamp_ms' }),
  snapshotCount: integer('snapshot_count'),
  totalSize: integer('total_size'),
  errorMessage: text('error_message'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
});

export const tasks = sqliteTable('tasks', {
  id: text('id').primaryKey(),
  repoId: text('repo_id').notNull().references(() => repos.id),
  userId: text('user_id').notNull().references(() => users.id),
  operation: text('operation').notNull(),
  status: text('status').notNull().default('queued'),
  context: text('context'),
  exitCode: integer('exit_code'),
  errorMessage: text('error_message'),
  log: text('log'),
  result: text('result'),
  startedAt: integer('started_at', { mode: 'timestamp_ms' }),
  completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
  durationMs: integer('duration_ms'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});

export const backupPlans = sqliteTable('backup_plans', {
  id: text('id').primaryKey(),
  repoId: text('repo_id').notNull().references(() => repos.id),
  userId: text('user_id').notNull().references(() => users.id),
  name: text('name').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  cronExpression: text('cron_expression').notNull(),
  paths: text('paths').notNull(),
  excludes: text('excludes'),
  tags: text('tags'),
  retentionPolicy: text('retention_policy'),
  maxFileCount: integer('max_file_count'),
  maxBytes: integer('max_bytes'),
  oneFileSystem: integer('one_file_system', { mode: 'boolean' }).notNull().default(false),
  excludeLargerThan: text('exclude_larger_than'),
  allowedBasePaths: text('allowed_base_paths'),
  preHook: text('pre_hook'),
  postHook: text('post_hook'),
  lastRunAt: integer('last_run_at', { mode: 'timestamp_ms' }),
  lastRunStatus: text('last_run_status'),
  nextRunAt: integer('next_run_at', { mode: 'timestamp_ms' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
});

export const backupPlanRuns = sqliteTable('backup_plan_runs', {
  id: text('id').primaryKey(),
  planId: text('plan_id').notNull().references(() => backupPlans.id),
  taskId: text('task_id').references(() => tasks.id),
  triggerType: text('trigger_type').notNull(),
  status: text('status').notNull().default('queued'),
  snapshotId: text('snapshot_id'),
  filesNew: integer('files_new'),
  filesChanged: integer('files_changed'),
  filesUnmodified: integer('files_unmodified'),
  bytesAdded: integer('bytes_added'),
  bytesProcessed: integer('bytes_processed'),
  durationMs: integer('duration_ms'),
  errorMessage: text('error_message'),
  retentionApplied: integer('retention_applied', { mode: 'boolean' }).notNull().default(false),
  startedAt: integer('started_at', { mode: 'timestamp_ms' }),
  completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});

export const restoreJobs = sqliteTable('restore_jobs', {
  id: text('id').primaryKey(),
  repoId: text('repo_id').notNull().references(() => repos.id),
  userId: text('user_id').notNull().references(() => users.id),
  taskId: text('task_id').references(() => tasks.id),
  snapshotId: text('snapshot_id').notNull(),
  sourcePaths: text('source_paths').notNull(),
  targetPath: text('target_path').notNull(),
  conflictStrategy: text('conflict_strategy').notNull().default('overwrite'),
  includePatterns: text('include_patterns'),
  excludePatterns: text('exclude_patterns'),
  verifyAfter: integer('verify_after', { mode: 'boolean' }).notNull().default(true),
  status: text('status').notNull().default('pending'),
  filesRestored: integer('files_restored'),
  bytesRestored: integer('bytes_restored'),
  durationMs: integer('duration_ms'),
  errorMessage: text('error_message'),
  startedAt: integer('started_at', { mode: 'timestamp_ms' }),
  completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});
